name: CI

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build container
        run: docker build -t unifi-controller .
      - name: start container
        run: docker run --detach --name unifi-controller --publish 8443:8443 unifi-controller
      - run: docker ps -a
      - run: sleep 30
      - run: curl --insecure --location --fail https://127.0.0.1:8443/
      - run: docker logs unifi-controller
