name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '4 4 * * 0'

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  GIT_AUTHOR_NAME: github-actions
  GIT_AUTHOR_EMAIL: actions@github.com

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'evgeni'
    steps:
    - uses: actions/checkout@v4
    - run: make update
    - name: Find out version
      run: echo UNIFI_VERSION=$(make version) >> $GITHUB_ENV
    - name: Open a PR
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "Update container to ${{ env.UNIFI_VERSION }}"
        branch: "bump-container"
        title: "Update container to ${{ env.UNIFI_VERSION }}"
        body: "Release notes: https://community.ui.com/releases/r/network/${{ env.UNIFI_VERSION }}"
        delete-branch: true
